# Generated by Django 2.2.6 on 2019-11-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_auto_20191106_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('chassi', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=15)),
                ('ano', models.IntegerField(max_length=5)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.Marcas')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.Modelo')),
            ],
        ),
    ]
