# Generated by Django 2.2.6 on 2019-11-07 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0003_marcas_modelo_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateField()),
                ('data_retorno', models.DateField()),
                ('valor', models.IntegerField(max_length=9)),
                ('observacao', models.TextField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.Cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.Veiculo')),
            ],
        ),
    ]
