# Generated by Django 2.2.6 on 2019-11-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0004_alguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alguel',
            name='data_locacao',
            field=models.DateField(auto_now=True),
        ),
    ]
