# Generated by Django 2.2.6 on 2019-11-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0005_auto_20191108_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
    ]
