# Generated by Django 2.2.6 on 2019-11-12 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0009_auto_20191111_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locadora.Marcas'),
            preserve_default=False,
        ),
    ]
