# Generated by Django 2.2.6 on 2019-11-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0011_auto_20191112_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='nome_marca',
            new_name='marca',
        ),
    ]
