# Generated by Django 2.2.6 on 2019-11-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0012_auto_20191112_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alguel',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(max_length=6),
        ),
    ]
