# Generated by Django 2.2.6 on 2019-11-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0013_auto_20191112_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alguel',
            name='valor',
            field=models.CharField(max_length=11),
        ),
    ]
