# Generated by Django 2.2.6 on 2019-11-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0014_auto_20191112_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alguel',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
