# Generated by Django 2.2.6 on 2019-11-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0015_auto_20191112_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'INATIVO')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alguel',
            name='valor',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(max_length=6),
        ),
    ]
