# Generated by Django 2.2.6 on 2019-11-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0019_remove_veiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'DISPONIVEL'), ('INDISPONIVEL', 'INDISPONIVEL')], max_length=14),
        ),
    ]
