# Generated by Django 2.2.6 on 2019-11-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0020_auto_20191113_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
