# Generated by Django 2.2.6 on 2019-11-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0022_alguel_data_recebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alguel',
            name='data_recebimento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
